name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Lint with flake8
      run: flake8 src/ tests/

    - name: Check formatting with black
      run: black --check src/ tests/

    - name: Type check with mypy
      run: mypy src/ tests/

    - name: Run tests
      run: pytest --cov=src/sqlmodelgen 